<?php

/**
 * @file
 * Primary module hook for weather module.
 */

use Drupal\registration\Form\RegistrationForm;

/**
 * Implements hook_entity_build.
 */
function registration_entity_type_alter(array &$entity_types): void {
  if (isset($entity_types['user'])) {
    $entity_types['user']->setFormClass('register', RegistrationForm::class);
  }
}

/**
 * Implements hook_theme().
 */
function registration_theme(): array {
  return [
    'registration' => [
      'variables' => [
        'link' => [],
      ],
    ],
  ];
}
